name: Static Code Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint-code:
    name: Code Linting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Restore Go caches
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Lint Go code
      uses: golangci/golangci-lint-action@v2
      with:
        skip-go-installation: true
        skip-pkg-cache: true
        skip-build-cache: true

  lint-config:
    name: Configuration Linting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Restore Go caches
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Lint Kubernetes manifests
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: config/
        config_file: .github/workflows/config/yamllint-k8s.yaml
        format: github

    - name: RBAC rules consistency
      run: |
        pushd hack/rbac-check
        go install .
        popd
        rbac-check
